# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170718_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='done',
        ),
        migrations.DeleteModel(
            name='Done',
        ),
    ]
